openapi: 3.0.0
info:
  title: 'Ticketing API Documentation'
  version: 1.0.0
paths:
  /api/tickets:
    get:
      operationId: getTicket
      responses:
        '200':
          description: Success
    post:
      operationId: storeTicket
      requestBody:
        $ref: '#/components/schemas/TicketSchema'
      responses:
        '201':
          description: Success
  '/api/tickets/{id}':
    put:
      operationId: updateTicket
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        $ref: '#/components/schemas/TicketSchema'
      responses:
        '200':
          description: Success
    delete:
      operationId: deleteTicket
      parameters:
        -
          name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
components:
  schemas:
    TicketSchema:
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: 'Issue with server'
        description:
          type: string
          example: 'The server is down since morning.'
        status:
          type: string
          enum:
            - open
            - in_progress
            - closed
          example: open
        priority:
          type: string
          enum:
            - low
            - medium
            - high
          example: medium
      type: object
